### ISSUE TITLE
[minor] Upvoting and downvoting multiple times crashed the site

### ISSUE THREAD

**Issue by thebriando** [wochen96/freebies#15]
**Describe the minor issue**
![image](https://user-images.githubusercontent.com/18522836/70285715-586b4f80-177d-11ea-9311-20aab0a8a147.png)

When clicking on a freebie and upvoting/downvoting back and forth multiple times, the site crashes sometimes.

**To Reproduce**
1. Go to 'https://freebiesuw.herokuapp.com/home'
2. Click on a freebie
3. Upvote and downvote

![image](https://user-images.githubusercontent.com/18522836/70285758-7afd6880-177d-11ea-993e-2657229ba61b.png)

**Expected behavior**
No crash should happen

**Screenshots**

**Device Used:**
 - Device: [e.g. MacBook Pro, iPhone 6]

**Additional context**

**Comment by tran6388-1672747** [comment]
# Real issue (sort of)

I have reproduced the error and I find that this will only happen when the user enters the upvote/downvote many time consecutively. When I try clicking the buttons, I have to click like 50 to 60 time continuously with rapid pace in order to see the error. So, I have implement a "catch" error that will solve the issue.

commit link: https://github.com/wochen96/freebies/commit/3870cff0a734e3e2913003e90684970742a1f48d
