### ISSUE TITLE
[minor] Votes can have negative values & a single user can vote multiple times

### ISSUE THREAD

**Issue by KeithSRoberts** [wochen96/freebies#19]
**Describe the minor issue**
If a user creates a new group and then subsequently makes vote on their newly created group, if the user ever edits and then submits that new group, the votes are reset to 0 and the user can vote again, causing some issues with the voting numbers.

**To Reproduce**
1. Login with Google
2. Click on 'New Post' in the navbar
3. Fill out the group and submit it
4. View the group you just made and upvote it.
5. Click edit on the same group
6. Click submit on the edit form
7. View the group again and downvote it this time, not the vote points

**Expected behavior**
Votes should persist when the user edits the group to prevent errors with the voting numbers

**Screenshots**
https://i.imgur.com/vWsQGQq.jpg

**Device Used:**
 - Device: Macbook 2015 
 - Browser Chrome

**Comment by tran6388-1672747** [comment]
# Real Failure

We understand the failure in the website for this part. However, we can not fix this bug together with other bug related to updating the votes. This is due to the fact that we need to create a new database in fire-base like users to store all the relevant information about the users and the posts. But, if we do that; then, we have restructure our entire code base from beginning to end to enable the work around of this. This will take a lot of time. We do not have enough time to redo this part in 1 days left before due day for fixing. We hope to look at this at later time and find way to work around this issue.
