### ISSUE TITLE
[minor] events can start and end at the exact same time

### ISSUE THREAD

**Issue by ssunni12** [wochen96/freebies#20]
Events can be scheduled to start and begin at the exact same time (like from 5:00 PM to 5:00 PM).

The example I used was the limited event named 'test' that started at 5 PM and ended at 5 PM.

**Comment by tran6388-1672747** [comment]
# Not real failure.

We are planning the the events to be entered at the same start and end day. This is exactly what we design the website to be. It is because we think that there are some users out there would want to enter events that can have the same start and end day. That may sound odd, but we want to leave this option open for users.
